### ISSUE TITLE
CdU 4 – Comando riscaldamento ON

### ISSUE THREAD

**Issue by mfinotti** [kairostech-sw/kairoshub-configuration#24]
L'HUB riceve sul topic di riferimento (identificativo dell'hub) il messaggio contenente il comando da eseguire. Il messaggio viene intercettato dall software e viene propagato nell'evento `INBOUND_EVENT`.

il modulo `kairoshubEvent` è in ascolto di questo evento e riceve il messaggio tipo: 

> {
>   "sender": "1234567",
>   "evenType": "HEATING_ON",
>   ................................................
>   ...............................................
> }

il modulo `kairoshubEvent` elabora l'eventType ricevuto e propaga un nuovo evento `AD_HEATING` che si occuperà di gestire l'accesione / spegnimento dell'impianto di riscaldamento. Viene passata come informazione aggiuntiva dell'evento il `sender` **che dovrà essere utilizzata alla fine dell'elaborazione**.

Una volta terminato il processo di accensione / spegnimento viene propagato un nuovo evento `AD_KAIROSHUB_NOTIFICATION` contenente le informazioni: 

> {
>   "sender": "1234567",   
>   "ncode": "HEATING_ON",
>   "type": "NOTICE",
> }

**N.B.** il sender può assumere **3 diversi valori, HUB,  * , valore numerico**. Se la notifica è una risposta ad un evento scatenato da remoto, allora il sender assumerà il valore numerico corrispondente al sender della richiesta. 
Se la notifica parte spontaneamente dall'HUB, in questo caso il valore sender potrà essere popolato con la wildcard `*` se la notifica dovrà essere spedita al cloud, invece conterrà il valore `HUB` se la notifica dovrà rimanere all'interno dell'HUB.

il modulo `Notification` che ascolta l'evento `AD_KAIROSHUB_NOTIFICATION` elabora il contenuto dell'evento e invia dapprima una notifica sull'HUB e a seconda del contenuto del _sender_ ( `*` o `1234567`) produce un messaggio sul cloud come di seguito: 

> {
>             "eventType" : {TYPE dell'evento ricevuto},
>             "systemCode": {systemCode},
>             "message" :  { messaggio preso dal dizionario con codice ncode} ,
>             "sender": {sender}
> }

invocare l'evento: 
`self.fire_event("HAKAFKA_PRODUCER_PRODUCE", topic="HASSIO", message=eventData)
`

**Comment by christianorsini** [comment]
### kairoshubNotification.json
Bisogna creare il file con i messaggi di notifica sul lato cloud e aggiungere `eventi` per creazione/aggiornamento del file al modulo `hello.py`.
### Sender Automazioni
Bisogna aggiungere alle automazioni dei programmi il sender  `HUB`

**Comment by mfinotti** [comment]
> ### kairoshubNotification.json
> Bisogna creare il file con i messaggi di notifica sul lato cloud e aggiungere `eventi` per creazione/aggiornamento del file al modulo `hello.py`.

La sincronizzazione del _vocabolario_ verrà implementata sulla falsa riga dei _settings_, quindi verrà aggiunta una automazione con trigger tempo e verrà invocato un evento. Sarà poi il modulo a richiamare la risorsa specifica per ottenere il file aggiornato. (Da implementare documentazione e task)


> ### Sender Automazioni
> Bisogna aggiungere alle automazioni dei programmi il sender `HUB`

No, è il modulo `Notification` che al momento di inviare il messaggio sul topic lo ricava dalla entity `system_code`.

**Comment by mfinotti** [comment]
### heating - turn on
API da richiamare attraverso verbo **POST**.
**REQUEST:** _POST_ `/system-command/heating/turn-on` body della request: `{}` 
**RESPONSE:**
Status code:
- 200 se l'invocazione del comando è andata a buon fine
- 301 se non si hanno i permessi per invocare la risorsa

Response body: 
```
{
  "data":{},
  "status":{
    "code": 200, (in base a status code)
    "message": "OK" (in base a status code)
  }
}
```

@christianorsini
