### ISSUE TITLE
Light Support

### ISSUE THREAD

**Issue by christianorsini** [kairostech-sw/kairoshub-configuration#42]
**_Aggiunto Supporto per Dispositivi di Illuminazione_**
## Implementazione Controllo Luce
I dispositivi sono raggruppati nel seguente modo:

> Gruppo contenente ogni dispositivo
> ---> Gruppo Luce della `Zona X00`
> ---------> Gruppo Luce `Zona XYY`
> ---------------> Dispositivi `RGB/WHITE/SWITCH`

Ogni dispositivo ha associato un sensore per indicarne la disponibilità

### Funzionalità Copia
Ogni zona di controllo luce permette di copiare le proprie impostazioni ai dispositivi della stessa `Zona X00`

### Programmazione Luci
I dispositivi possono essere impostati in base a tre valori:
  - Programmato
  - Automatico
  - Disattivo

#### Programmato
Permette di impostare tre modalità in base ai giorni di attivazione e con orari di attivazione personalizzabili:
  - Feriale
  - Festivi
  - Tutti

#### Automatico
Attiva l'illuminazione in base all'elevazione del sole.
Viene disattivata dopo un valore impostato da utente. `Default: 5 ore`

### Storicizzazione
Verificare se sono necessari dati da storicizzare

## TODO
- [ ] File con informazioni relative ai programmi

**Comment by christianorsini** [comment]
@mfinotti

**Comment by mfinotti** [comment]
Verificare problema tap su card che contiene combobox. (problema presente anche in Impostazioni / sistema)
